---
sudo: required
services: [docker]
language: python
python:
  - "2.6"
before_install:
  - docker pull lpenz/openyuma
  - sudo pip install docker-py==1.5.0 ncclient
  - printf 'Hosts *\n\tStrictHostKeyCheckin no\n\tUserKnownHostsFile /dev/null\n' >> ~/.ssh/config
  - git submodule update --init --recursive
  - . ./ansible/hacking/env-setup
jobs:
  include:
      - env: [ ACTION=module ]
        script:
          - cd playbooks
          - ansible-playbook --module-path=$PWD/../ansible-modules-extras/network/netconf -i localhost, -c local playbook-openyuma.yml
      - env: [ ACTION=connection, ANSIBLE_HOST_KEY_CHECKING=False ]
        script:
          - docker run -d --name openyuma -p 3830:830 lpenz/openyuma
          - cd playbooks
          - ansible-playbook -vvv --module-path=$PWD/../ansible-modules-extras/network/netconf -i inventory playbook-netconfconn.yml
