---
- name: pull an image
  docker_image:
    name: lpenz/openyuma

- name: start openyuma
  docker_container:
    name: openyuma
    state: started
    image: lpenz/openyuma
    ports: 3830:830

- name: wait for netconf port
  wait_for:
    host: 127.0.0.1
    port: 3830
    delay: 5
