---
- name: start netopeer
  docker:
    name: netopeer
    state: restarted
    image: lpenz/netopeer
    expose:
      - 830
    ports: 3830:830

- name: wait for netconf port
  wait_for:
    host: 127.0.0.1
    port: 3830
    delay: 5
